### ISSUE TITLE
Error: Can't rename variables in this context.

### ISSUE THREAD

**Issue by psads-git** [tidyverse/dtplyr#314] opened 2021-11-18 11:47 UTC
The following example gives the indicated error. However, if using `dplyr` instead of `dtplyr`, no error is returned.

``` r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

df1 = data.table(
  ID = c("a1", "a2", "a3", "a4", "a5", "a6", "a7"),
  "string1" = c("x2", "g3", "n2", "m3", "2w", "ps2", "kg2"),
  "S_2018_p" = c(3,5,11,3,9,22,6),
  "S_2019_p" = c(3,5,6,21,1,4,0),
  "S_2020_p" = c(0,4,13,9,16,7,9),
  "S_2021_p" = c(4,0,3,8,5,4,6),
  "string2" = c("si", "q2", "oq", "mx", "ix", "p2", "2q"))

df2 <- lazy_dt(df1)

df2 %>%
  mutate(
    across(
      where(is.numeric),
      ~ if_else(get(cur_column()) > 10, 0, get(cur_column()))))
#> Error: Can't rename variables in this context.
```

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment] 2021-11-18 12:07
Duplicate of #271. Unfortunately, predicates using the column type do not work.

**Closed by mgirlich** 2021-11-18 12:07 UTC
