### ISSUE TITLE
`where()` within `across()` returns an error of "Can't rename variables in this context"

### ISSUE THREAD

**Issue by nigeljmckernan** [tidyverse/dtplyr#183] opened 2021-02-04 23:10 UTC
This is my first bug report on GitHub, so please forgive me if I missed a key troubleshooting step!

Trying to use `where()` within `across()` inside of `summarise()` returns an error of "Can't rename variables in this context".

Using the latest development version of `dtplyr` (version 1.01.9000) with version 1.0.4 of `dplyr`.

Tried recompiling `dplyr` from source, as well as making sure to install `dtplyr` through `devtools::install_github("tidyverse/dtplyr")`.

Also tried on a clean install of R (4.0.3), RStudio (1.4.1103), with subsequent clean installs `dplyr` and development-version `dtplyr`.

```r
library(nycflights13)
library(dplyr)
library(dtplyr)

flights %>%
    
     lazy_dt() %>%
     
     group_by(year,
              month) %>%
     
     summarise(across(where(is.numeric), mean)) %>%

     ungroup() %>%
     
     collect()
# Error: Can't rename variables in this context.
```
Yet works fine in a regular `dplyr` context.

```r
flights %>%
     
     # lazy_dt() %>%

     group_by(year,
              month) %>%
     
     summarise(across(where(is.numeric), mean)) %>%

     ungroup() %>%
     
     collect()
#`summarise()` has grouped output by 'year'. You can override using the `.groups` argument.
# A tibble: 12 x 14
#    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay flight air_time distance  hour minute
#   <int> <int> <dbl>    <dbl>          <dbl>     <dbl>    <dbl>          <dbl>     <dbl>  <dbl>    <dbl>    <dbl> <dbl>  <dbl>
# 1  2013     1  16.0       NA          1341.        NA       NA          1548.        NA  1959.       NA    1007.  13.2   25.2
# 2  2013     2  14.7       NA          1342.        NA       NA          1547.        NA  1956.       NA    1001.  13.2   25.2
# 3  2013     3  16.0       NA          1354.        NA       NA          1546.        NA  2003.       NA    1012.  13.3   25.4
# 4  2013     4  15.4       NA          1351.        NA       NA          1537.        NA  1979.       NA    1039.  13.3   26.0
# 5  2013     5  16.0       NA          1345.        NA       NA          1533.        NA  1986.       NA    1041.  13.2   26.6
# 6  2013     6  15.6       NA          1346.        NA       NA          1527.        NA  1935.       NA    1057.  13.2   27.2
# 7  2013     7  16.2       NA          1347.        NA       NA          1521.        NA  1959.       NA    1059.  13.2   27.1
# 8  2013     8  15.8       NA          1345.        NA       NA          1519.        NA  1960.       NA    1062.  13.2   26.9
# 9  2013     9  15.6       NA          1335.        NA       NA          1534.        NA  2026.       NA    1041.  13.1   26.4
#10  2013    10  16.0       NA          1336.        NA       NA          1539.        NA  2008.       NA    1039.  13.1   26.4
#11  2013    11  15.3       NA          1342.        NA       NA          1545.        NA  1962.       NA    1050.  13.2   25.7
#12  2013    12  15.7       NA          1345.        NA       NA          1543.        NA  1927.       NA    1065.  13.2   26.3

```

Other `tidyselect` helper functions that I've tried work, including: `everything()`, `all/any_of()`, `contains()`, and `starts/ends_with()`.

```r
vars <- c("arr_time","carrier","origin")

flights %>%
    
    lazy_dt() %>%
    
    group_by(year,
             month) %>%
    
    summarise(across(all_of(vars), last)) %>%

    ungroup() %>%
    
    collect()
# A tibble: 12 x 5
#    year month arr_time carrier origin
#   <int> <int>    <int> <chr>   <chr> 
 #1  2013     1       NA UA      LGA   
 #2  2013     2       NA UA      JFK   
 #3  2013     3       NA UA      EWR   
 #4  2013     4       NA US      LGA   
 #5  2013     5       NA UA      LGA   
 #6  2013     6       NA EV      LGA   
 #7  2013     7       NA MQ      LGA   
 #8  2013     8       NA EV      LGA   
 #9  2013     9       NA MQ      LGA   
#10  2013    10       NA B6      LGA   
#11  2013    11       NA MQ      LGA   
#12  2013    12       NA UA      JFK   
```

Happens outside of a grouped context as well.

```r
flights %>%
     
     lazy_dt() %>%
     
     summarise(across(where(is.character), last)) %>%
     
     collect()
# Error: Can't rename variables in this context.\
```

**Comment by hadley** [comment] 2021-02-04 23:22
This is basically a duplicate of #583; there's no way to use `across()` with predicate functions in dbplyr, and we need to return a clearer message.

**Closed by hadley** 2021-02-04 23:22 UTC
