### ISSUE TITLE
mutate_if & select_if fails to be translated

### ISSUE THREAD

**Issue by ColinFay** [tidyverse/dtplyr#103] opened 2019-09-20 13:23 UTC
Hello, 

It seems that `mutate_if()` & `select_if` fails to be translated to `{data..table}` code. 

Reprex:

``` r
iris <- head(iris, 10)
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)
# From doc
iris %>% 
  mutate_if(is.factor, as.character)
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1           5.1         3.5          1.4         0.2  setosa
#> 2           4.9         3.0          1.4         0.2  setosa
#> 3           4.7         3.2          1.3         0.2  setosa
#> 4           4.6         3.1          1.5         0.2  setosa
#> 5           5.0         3.6          1.4         0.2  setosa
#> 6           5.4         3.9          1.7         0.4  setosa
#> 7           4.6         3.4          1.4         0.3  setosa
#> 8           5.0         3.4          1.5         0.2  setosa
#> 9           4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
# With dtplyr
lazy_dt(iris) %>% 
  mutate_if(is.factor, as.character)
#> Source: local data table [?? x 5]
#> Call:   copy(`_DT1`)[, `:=`()]
#> Error in `[.data.table`(copy(`_DT1`), , `:=`()): In `:=`(col1=val1, col2=val2, ...) form, all arguments must be named.

# From doc
iris %>% 
  mutate_if(is.double, as.integer)
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1             5           3            1           0  setosa
#> 2             4           3            1           0  setosa
#> 3             4           3            1           0  setosa
#> 4             4           3            1           0  setosa
#> 5             5           3            1           0  setosa
#> 6             5           3            1           0  setosa
#> 7             4           3            1           0  setosa
#> 8             5           3            1           0  setosa
#> 9             4           2            1           0  setosa
#> 10            4           3            1           0  setosa
# With dtplyr
lazy_dt(iris) %>% 
  mutate_if(is.double, as.integer)
#> Source: local data table [?? x 5]
#> Call:   copy(`_DT2`)[, `:=`()]
#> Error in `[.data.table`(copy(`_DT2`), , `:=`()): In `:=`(col1=val1, col2=val2, ...) form, all arguments must be named.

# With dplyr
iris %>% 
  select_if(is.factor)
#>    Species
#> 1   setosa
#> 2   setosa
#> 3   setosa
#> 4   setosa
#> 5   setosa
#> 6   setosa
#> 7   setosa
#> 8   setosa
#> 9   setosa
#> 10  setosa

# With dtplyr
lazy_dt(iris) %>% 
  select_if(is.factor)
#> Source: local data table [?? x 0]
#> Call:   `_DT3`[, 0L]
#> 
#> 
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2019-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It seems that there is no `dtplyr:::mutate_if` / `dtplyr:::select_if`. 

Are there plans to integrate them? 

Maybe a warning in the meantime would be nice, saying they are not implemented, instead of returning an error / empty DT.

**Comment by hadley** [comment] 2019-09-20 17:16
Duplicate of #99?

**Closed by hadley** 2019-09-20 17:16 UTC
