### ISSUE TITLE
S3 method overloading on namespace load

### ISSUE THREAD

**Issue by bguillod** [tidyverse/dtplyr#312] opened 2021-10-28 12:50 UTC
I started to use dtplyr but there is a behaviour I cannot understand - I'm afraid I do not know whether it's a beginners' misunderstanding or a bug, but I cannot find any documentation about this so I decided to post it here.

In essence, creating a lazy data.table alters the original variable, as in this minimal reprex:
```r
# defining a dummy data table
x <- data.table::data.table(a=1:5, b=letters[1:5])

# operation (1): applying a mutate statement to it - this works fine
x |> dplyr::mutate(c=paste(a,b))

# creating the corresponding lazy data table
x2 <- dtplyr::lazy_dt(x)

# applying dplyr::mutate to x2 and obtaining it with as.data.table works fine
#    and returns a data.table object.
x2 |> dplyr::mutate(c=paste(a,b)) |> data.table::as.data.table()

# but running again operation (1) seems to re-create a dtplyr object,
#    leading to a different result than in the first call above.
class(x |> dplyr::mutate(c=paste(a,b)))                                                                                                                                                                          
# [1] "dtplyr_step_mutate" "dtplyr_step"
```

Note that also after assigning x2 result into a new variable, applying any dplyr verb re-creates a dtplyr object:
```r
y <- x2 |> dplyr::mutate(c=paste(a,b)) |> data.table::as.data.table()
y
#     a b   c
# 1: 1 a 1 a
# 2: 2 b 2 b
# 3: 3 c 3 c
# 4: 4 d 4 d
# 5: 5 e 5 e

class(y |> dplyr::mutate(d=0))
# [1] "dtplyr_step_mutate" "dtplyr_step"
```

I did not expect either of these two behaviours. Is it intended that any object, once converted to a lazy data table, cannot anymore fully loose the lazy property?

Is there a way to force an object to be a normal data.table?

Or is there something fundamental I am missing, which might be documented somewhere?

I am using the following versions:
- R: 4.1.1
- dplyr: 1.0.7
- dtplyr: 1.1.0
- data.table: 1.14.2

**Comment by bguillod** [comment] 2021-11-01 09:15
Great, so we agree on this point @mgirlich.

In addition IMHO even if this was changed to happen only when using `library(dtplyr)` it would cause an issue for packages would might want to have `dtplyr` as a dependency, because loading their package also would cause that issue. Or more generally, because loading `dtplyr` prevents some functionalities from other packages to work it makes `dtplyr` far less attractive...

**Comment by hadley** [comment] 2021-11-28 19:55
The behaviour was implemented here: https://github.com/tidyverse/dtplyr/commit/6ba37f36967758cf6b644cc52874f6fd288d50d8

I feel like it's probably correct; using dplyr generics on data.table objects seems likely to only work by coincidence.

**Comment by mmyrte** [comment] 2021-11-30 15:55
Yes, that is true. However, when you apply a dplyr generic to a data.frame like object (including data.tables), you expect to receive a data.frame-like object in return (as per the docs). This probably isn't super safe in the first place - you won't know for certain if the returned object will inherit the same class as the input, or whether it will be coerced to a tibble. However, it will certainly behave like a data.frame. I would dare to make the assumption that people rely on that behaviour of dplyr generics. When a simple `.onLoad` alters its behaviour, people like @bguillod and I get confused. 😃

There is certainly some convenience in the current behaviour when working exclusively with dtplyr _and_ interactively. But as @mgirlich [shows](https://github.com/tidyverse/dtplyr/issues/312#issuecomment-954450104), it introduces hard-to-debug issues in other places.

Would it not be safer, as Benoît suggests, to require users to coerce to lazy_dt explicitly?

**Comment by hadley** [comment] 2021-11-30 17:56
@mmyrte Would it be better to have never introduced these methods? Quite possibly. Is removing them now high risk because folks are likely to depend on them? I'd say yes. So fixing this requires some careful analysis of the failure modes.

**Comment by mmyrte** [comment] 2021-11-30 19:47
I'm not sure that dropping these exports would be a breaking change. Instead of operating on a lazy data.table, the dplyr verbs would simply coerce to tibble (or not) - and since `as_tibble()` or such is expected at the end of a pipeline, the result would maintain its class. 

There would be a reasonable performance hit for those relying on the current functionality. I cannot spontaneously imagine a way of non-intrusively diagnosing the issue from within this package (I could think of overloading as_tibble etc to check if such a coercion is even necessary, and to print a message if it's not, but am doubtful that it's not too aggressive.)

**Comment by mmyrte** [comment] 2022-01-07 22:34
What if we set an option before loading the namespace that suppresses the overloading? It wouldn't be _nice_, but it wouldn't break anything.

**Comment by guersam** [comment] 2022-04-06 09:23
I have an existing codebase to introduce dtplyr for better performance, but it goes broken when I load dtplyr package and it was difficult to find the cause.

**Comment by hadley** [comment] 2022-07-06 04:56
This just caught me too, so I think we should do the analysis to figure out how to remove these methods.

**Comment by markfairbanks** [comment] 2022-07-06 14:27
> so I think we should do the analysis to figure out how to remove these methods.

What would we have to do for this? Remove the methods and run revdeps?

Another thought - maybe a safe way would be to change these so we always use `as.data.table()` at the end of `.data.table` methods? Sort of an eager evaluation option?

So `mutate.data.table()` would become:

```r
mutate.data.table <- function(.data, ...) {
  .data <- lazy_dt(.data)
  out <- mutate(.data, ...)
  as.data.table(out)
}
```

**Comment by hadley** [comment] 2022-07-06 18:35
Yeah, maybe we just pull it and run the revdeps to see what happens. Package code is only a proxy for user code, but if there aren't any problems, it likely suggests there will be limited impact.

We could also provide some easy way to explicitly turn back on with a function that manually did the S3 method registration.

**Comment by markfairbanks** [comment] 2022-07-06 19:32
> Yeah, maybe we just pull it and run the revdeps to see what happens.

Sounds good.

And as I think about this more - it seems like it would be very tough for this to break code. You can use `collect()`/`as.data.table()` on data.tables and tibbles. The only surprising part would be `collect()` returning a data.table instead of a tibble when the data was ungrouped.

``` r
library(dplyr, warn.conflicts = FALSE)
library(data.table, warn.conflicts = FALSE)

df <- data.table(x = 1:3, y = c("a", "a", "b"))

df %>%
  mutate(double_x = x * 2) %>%
  collect()
#>        x      y double_x
#>    <int> <char>    <num>
#> 1:     1      a        2
#> 2:     2      a        4
#> 3:     3      b        6
```

So it might slow down some parts of user code since it will be using dplyr instead of dtplyr, but it would be tough to actually break something (I think). Unless for some reason someone was relying on the fact that the end of their chain was a `dtplyr_step`, but that seems highly unlikely.

Am I missing an obvious case?

**Comment by hadley** [comment] 2022-07-06 20:14
@markfairbanks yeah, I think you're right. I guess the main downside is that folks might get an unexpected performance decrease if they'd been relying on dtplyr activating automatically.

**Comment by markfairbanks** [comment] 2022-07-06 21:15
Maybe we wait for the dplyr 1.1.0 release to make the dtplyr release dropping the `.data.table` methods? That would mitigate the performance loss.

The biggest performance differences I've found between data.table/dplyr was from `arrange` and grouped functions. The dev version of `dplyr::arrange()` is already relatively close to data.table now that it orders in the C locale and I'm guessing grouped operations will be somewhat close as well once https://github.com/tidyverse/dplyr/pull/6297 is merged.

Not to mention that `select`/`mutate` are faster in dplyr unless you use modify-by-reference in data.table (then data.table/dplyr are somewhat comparable).

Note: These tests are run with the dev versions of both dplyr & data.table.

Note2: `dplyr::arrange()` was 20-30x slower than data.table before dplyr's recent update.

``` r
library(data.table, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

setDTthreads(4)

set.seed(123)

random_strings <- c('OoVt', 'wCbu', 'cXxX', 'jdFu', 'MCRx',
                    'ukhz', 'ikce', 'PHyu', 'jpBY', 'nLQM')

data_size <- 10000000

df <- data.table(
  a = sample(1:20, data_size, TRUE),
  b = sample(1:20, data_size, TRUE),
  c = sample(random_strings, data_size, TRUE),
  d = sample(random_strings, data_size, TRUE)
)

# Using dev versions of both dplyr & data.table
bench::mark(
  dt_arrange = df[order(c, a)],
  dplyr_arrange = arrange(df, c, a),
  dt_select = df[, .(a, b, c)],
  dplyr_select = select(df, a, b, c),
  dt_summarize = df[, .(mean_a = mean(a), med_b = median(b)), by = .(c, d)],
  dplyr_summarize = df |>
    group_by(c, d) |>
    summarize(mean_a = mean(a), med_b = median(b), .groups = "drop"),
  dt_mutate = copy(df)[, double_a := a * 2],
  dplyr_mutate = mutate(df, double_a = a * 2),
  check = FALSE, iterations = 11
)
#> # A tibble: 8 × 6
#>   expression           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 dt_arrange      645.97ms  648.7ms      1.54   268.8MB     6.94
#> 2 dplyr_arrange   841.26ms  869.1ms      1.15   392.9MB     2.30
#> 3 dt_select        55.45ms   59.8ms     16.4    305.4MB    43.7 
#> 4 dplyr_select      1.84ms    2.1ms    457.     863.7KB     0   
#> 5 dt_summarize       362ms  364.2ms      2.68   344.9MB     7.16
#> 6 dplyr_summarize 612.51ms  630.8ms      1.59   370.5MB     7.93
#> 7 dt_mutate        87.88ms  109.1ms      9.17   305.2MB    50.4 
#> 8 dplyr_mutate     16.98ms   17.2ms     48.2     76.4MB    18.1
```

**Comment by hadley** [comment] 2022-07-10 21:21
Yeah, I think that's a good approach.

Would you mind doing a PR to remove the methods? Then I can run the revdepchecks on that branch. And assume that goes well we can plan for a dtplyr release after the next dplyr release.

**Comment by markfairbanks** [comment] 2022-07-11 01:29
Yep, sounds good.

**Closed** 2022-07-15 19:26 UTC
