### ISSUE TITLE
Function calls in functions can not access to environment variables in parent functions

### ISSUE THREAD

**Issue by psychelzh** [tidyverse/dtplyr#386] opened 2022-08-15 12:08 UTC
@markfairbanks Still fails in such circumstances (seemingly, function calls in functions can not access environment variables, either):

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dtplyr)
f <- function(x, y, .v = "x") {
  inner_join(
    mutate(x, a = .v),
    y,
    by = character()
  )
}
x <- data.frame(a = "y")
y <- data.frame(b = "x")
f(x, y)
#>   a b
#> 1 x x
lazy_dt(x) |> 
  f(y)
#> Error in .checkTypos(e, names_x): Object '.v' not found. Perhaps you intended .cross_join_col
```

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

_Originally posted by @psychelzh in https://github.com/tidyverse/dtplyr/issues/317#issuecomment-1214932833_

**Comment by markfairbanks** [comment] 2022-08-15 14:12
Simpler reprex:

``` r
library(dplyr)
library(dtplyr)

f <- function(x, .v = "x") {
  mutate(x, a = .v)
}

x <- data.frame(a = "y")

lazy_dt(x) |> 
  f(y)
#> Error in eval(jsub, SDenv, parent.frame()): object '.v' not found
```

**Comment by markfairbanks** [comment] 2022-08-15 14:24
The issue - `lazy_dt()` marks the global environment as the evaluation environment. But in this case we need the evaluation environment to be the function environment of `f()` because that's where `.v` exists.

``` r
library(dplyr, w = FALSE)
library(dtplyr)

f <- function(x, .v = "x") {
  mutate(x, a = .v)
}

x <- lazy_dt(data.frame(a = "y"))

x$env
#> <environment: R_GlobalEnv>
```

**Comment by markfairbanks** [comment] 2022-08-15 15:06
You could always grab the evaluation environment from the `...` passed to `mutate()` (or `filter`/`summarize`/etc.) by capturing the dots as quosures and extracting the environment from them. This solves the original issue.

However this would fail if two functions (let's say a `mutate()` and a `filter()`) were each defined in separate function environments.

``` r
my_mutate <- function(x, .v = "x") {
  mutate(x, a = .v)
}

my_filter <- function(x, .val = "x") {
  filter(x, a == .val)
}

x <- lazy_dt(data.frame(a = "y"))

x %>%
  my_mutate() %>%
  my_filter()
```

I'm not too familiar with "combining" environments (and possible issues or performance implications), but as far as I can tell that would be the only way to deal with this.

**Comment by eutwt** [comment] 2022-08-15 15:21
Until/unless this is fixed in dtplyr, a workaround is to inject the variable

``` r
library(dplyr, w = FALSE)
library(dtplyr)

f <- function(x, .v = "x") {
  mutate(x, a = !!.v)
}

x <- data.frame(a = "y")

lazy_dt(x) |> 
  f()
#> Source: local data table [1 x 1]
#> Call:   copy(`_DT1`)[, `:=`(a = "x")]
#> 
#>   a    
#>   <chr>
#> 1 x    
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by eutwt** [comment] 2022-08-15 15:27
It looks like this works in dbplyr 

``` r
library(dplyr, w = F)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
x <- data.frame(a = "y")
copy_to(con, x)

f <- function(x, .v = "test") {
  mutate(x, a = .v)
}

tbl(con, 'x') %>% 
  f() %>% 
  show_query()
#> <SQL>
#> SELECT 'test' AS `a`
#> FROM `x`
```

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by psychelzh** [comment] 2022-08-15 15:56
Perhaps this bug is the same as #260

**Comment by eutwt** [comment] 2022-08-15 23:58
Yes, that looks like the same bug.

I think we need a dtplyr equivalent of `dbplyr:::partial_eval_quo`. Funnily, the [function definition in dbplyr](https://github.com/tidyverse/dbplyr/blob/82e5ed1c51247c55248b4067d29462de1c97a135/R/tidyeval.R#L109) contains the comment "no direct equivalent in `dtplyr`". 

We're already capturing the arguments as quosures so we have the environment and just need to do the injection. Example:

``` r
library(dplyr, w = F)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
x <- data.frame(a = "y")
copy_to(con, x)
dbp_tbl <- tbl(con, 'x')

f <- function(x, .v = "test") {
  mutate(x, a = .v)
}

x <- rlang::new_quosure(
  expr(paste0(a, .v)), 
  env = as.environment(list(.v = 'injected', a = 'not used'))
)
x
#> <quosure>
#> expr: ^paste0(a, .v)
#> env:  0x7fa9c7fbc1e8
dbplyr:::partial_eval_quo(x, data = dbp_tbl)
#> <quosure>
#> expr: ^paste0(a, "injected")
#> env:  0x7fa9c7fbc1e8
```

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by eutwt** [comment] 2022-08-16 00:55
Ignore my previous comment. I think the issue is just that because `.v` starts with `.`, dtplyr treats it as a `data.table` symbol e.g. `.N` and doesn't do any injection.

https://github.com/tidyverse/dtplyr/blob/ca698f4f8674003141d784ef72a0afa2ebf1d98d/R/tidyeval.R#L80

**Comment by psychelzh** [comment] 2022-08-16 01:19
> Ignore my previous comment. I think the issue is just that because `.v` starts with `.`, dtplyr treats it as a `data.table` symbol e.g. `.N` and doesn't do any injection.
> 
> https://github.com/tidyverse/dtplyr/blob/ca698f4f8674003141d784ef72a0afa2ebf1d98d/R/tidyeval.R#L80

Yeah, you are correct! So this won't fix? Users should inject it by themselves?

**Comment by eutwt** [comment] 2022-08-16 01:27
At minimum, we can just do a better job of detecting whether the variable is a data.table symbol like `.N` (e.g. `.v` is not), by checking against an actual list `c(".SD", ".BY", ".N", ".I", ".GRP", ".NGRP")`

But, to be honest I'm not sure why that branch of the `if else` is there at all. After removing lines 80-82 completely all our tests still pass. And the only time I can think that you'd get into that is from user-supplied data.table symbols e.g. 

```{r}
lazy_dt(data.frame(a = "y")) %>% 
  mutate(new = .N)
```

But this still works with those 3 lines deleted. @markfairbanks do you see a reason for that check to exist?

**Closed** 2022-08-16 15:20 UTC
Labels: bug
