### ISSUE TITLE
mutate_at doesn't seem to be working

### ISSUE THREAD

**Issue by torema-ed** [tidyverse/dtplyr#106] opened 2019-09-25 07:25 UTC
Hi Hadley, I was giving dtplyr a spin (just installed the GitHub version an hour ago) and was trying to change a few column types using `dplyr::mutate_if()` when errors came up. `dplyr::mutate()` seems to be working fine though.

**Mini-test script/Reprex??**
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
library(magrittr)

test_dt <- data.table(id = c("a", "b", "c", "d", "e"),
                      test_data = 1:5)

test_dt %<>% lazy_dt(immutable = FALSE)

test_dt %<>% mutate(id = factor(id)) %>%
  as.data.table()

test_dt %<>% mutate_at(vars(id), factor) %>%
  as.data.table()

Thank you for the awesome work! :)

**Comment by hadley** [comment] 2019-10-04 12:26
Duplicate of #109 (I'm collecting all the scoped problems in the same place since they likely have the same underlying cause)

**Closed by hadley** 2019-10-04 12:26 UTC
