### ISSUE TITLE
Bug in summarise_if predicate evaluation when lazy_dt invoked

### ISSUE THREAD

**Issue by vlahm** [tidyverse/dtplyr#99] opened 2019-09-04 02:48 UTC
Predicate of `summarise_if` incorrectly evaluates data type tests.

```r
lazy_dt(mtcars) %>%
    group_by(cyl) %>%
    summarise_if(is.numeric, mean) %>%
    as.data.frame()

#  cyl
#1   6
#2   4
#3   8

#for comparison
mtcars %>%
    group_by(cyl) %>%
    summarise_if(is.numeric, mean) %>%
    as.data.frame()

#  cyl      mpg     disp        hp     drat       wt     qsec        vs        am
#1   4 26.66364 105.1364  82.63636 4.070909 2.285727 19.13727 0.9090909 0.7272727
#2   6 19.74286 183.3143 122.28571 3.585714 3.117143 17.97714 0.5714286 0.4285714
#3   8 15.10000 353.1000 209.21429 3.229286 3.999214 16.77214 0.0000000 0.1428571
```

**Comment by hadley** [comment] 2019-10-04 12:27
Duplicate of #109 (I'm collecting all the scoped problems in the same place since they likely have the same underlying cause)

**Closed by hadley** 2019-10-04 12:27 UTC
